# Generated by Django 4.1.3 on 2022-11-22 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_subscriber_subscribercategory_category_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscriber',
            field=models.ManyToManyField(through='news.SubscriberCategory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscribercategory',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
